# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DiffPose',
                'doc_host': 'https://vivekg.dev',
                'git_url': 'https://github.com/eigenvivek/DiffPose',
                'lib_path': 'diffpose'},
  'syms': {}}
